#!/usr/bin/env python3
# -*- coding: utf-8 -*-

#=============================
# Zdaemon Class for generating a server.
#=============================
class ZDaemonServer():

    common = "";

    def __init__(self, commonclass):
        self.common = commonclass;

    ###
    # ASK_Gamemode 
    # Asks to input the gamemode chosen.
    ###   
    def Gamemode_Name(self, mode):
        if (not mode): return "Deathmatch"; 
        elif (mode == 1): return "Team Deathmatch";
        elif (mode == 2): return "Cooperation";
        elif (mode == 3): return "Capture the Flag";
        elif (mode == 4): return "Survival";
        elif (mode == 5): return "Double Domination";
        return "Deathmatch"; #Default Mode
        
    def ASK_Gamemode(self):
        msg = "What Gamemode would you like to play?\n\
[0] Deathmatch\n\
[1] Team Deathmatch\n\
[2] Cooperation\n\
[3] Capture the Flag\n\
[4] Survival\n\
[5] Double Domination";
        
        iChoice = self.common.ClampQuestion(0, 5, msg, "What gamemode will the server use?");
        self.gamemode = iChoice;
 
    def ASK_Difficulty(self):
        
        if (self.gamemode == 2 or self.gamemode == 4):
        
            msg = "What Difficulty do you want to have?\n\
[0] I'm too young to die. (Easy+2x ammo)\n\
[1] Hey, not too rough. (Easy)\n\
[2] Hurt me plenty (Normal)\n\
[3] Ultra-Violence (Hard)\n\
[4] NIGHTMARE! (Hard+Fast monsters+ monsters respawn+2x ammo)";
        
            iChoice = self.common.ClampQuestion(0, 4, msg, "What difficulty will the server have?");
            self.skill = iChoice+1; 
        else:
            self.skill = 5; #Automatically Nightmare for PvP servers.
    ###
    # ASK_BasicInfo 
    # Asks to input the gamemode chosen.
    ###   
    def ASK_DMFlags(self):
        self.iClients = self.common.ClampQuestion(2, 100, "", "How many clients would join the server?");
        self.iPlayers = self.common.ClampQuestion(2, self.iClients, "", "How many players?");
    
    def ASK_ClientInfo(self):
        self.iClients = self.common.ClampQuestion(2, 100, "", "How many clients would join the server?");
        self.iPlayers = self.common.ClampQuestion(2, self.iClients, "", "How many players?");
    
    
    def WriteCFG(self):
        
        fputs ("// Zdaemon Configuration file for " + self.common.Hostname);
        fputs ("// Creation date: "+date()); #ToDo
        fputs ("// IWAD: " + self.common.IWAD);
        if (self.common.PWAD):
            fputs ("// PWAD(s): "+ self.common.PWAD) #Case if we host PWADs
        fputs ("// Generated by Ch0wW's Doom Server Generator - https://github.com/Ch0wW");
        
        fputs ("");
        fputs ("//------------");
        fputs ("// General Server Informations");
        fputs ("//------------");
        fputs ('set hostname "'+self.common.Hostname+'"')
        fputs ('set website "'+self.common.WWWURL+'"')
        fputs ('set email "'+self.common.Mail+'"')
        fputs ('set motd "" // Please set your MOTD (reminder: <br> goes to a new line');
        fputs ("");
        fputs ('set password "'+self.common.Password+'"')
        fputs ('set join_password "'+self.common.JoinPassword+'"')
        fputs ("");
        fputs ("//------------");
        fputs ("// General Server Settings");
        fputs ("//------------");
        fputs ('set maxclients "'+str(self.iClients)+'"')
        fputs ('set maxplayers "'+str(self.iPlayers)+'"')
        fputs ('set gametype "'+str(self.gamemode)+'" // '+self.Gamemode_Name(self.gamemode));
        fputs ('set skill "'+str(self.skill)+'"');
        fputs ("");       
        
    def Run(self):
        self.common.ASK_IWAD();
        self.common.ASK_Hostname();
        self.common.ASK_MailAddress();
        self.common.ASK_WebAddress();
        self.common.ASK_Password();
        
        self.ASK_ClientInfo();
        
        # Select Gamemode (and difficulty)
        self.ASK_Gamemode();
        self.ASK_Difficulty();
        
        #self.ASK_DMFlags()
        
        # Printing our server.
        print ("=========================================");
        print (" - Server Infos - ");
        print ("► IWAD / PWADs: "+ self.common.IWAD + " / " + self.common.PWAD);
        print ("► Hostname: " + self.common.Hostname);    
        print ("► Contact Mail: "+ self.common.Mail);
        print ('► Password / JoinPassword: "'+ self.common.Password + '" / "' + self.common.JoinPassword+'"');
        print ("► DL Website: "+ self.common.WWWURL);
        print ("");
        print ("► Clients / Players: "+ str(self.iClients) + " / " + str(self.iPlayers));
        print ("");
        print ("► Gamemode: " + self.Gamemode_Name(self.gamemode))
        print ("► Skill: " + str(self.skill))
        print ("=========================================");